kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
       claimName: test-claim
  containers:
    - name: task-pv-container
      image: nginx:1.13.3-alpine
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nfs-pvc
