apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-delete
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual-delete
  nfs:
    path: /data/nfs
    server: 192.168.56.51
