apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-retain
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-retain
  nfs:
    path: /data/nfs
    server: 192.168.56.51
