apiVersion: v1
kind: Pod
metadata:
  name: rng-pod
  namespace: schedule-demo
  labels:
    app: myapp
    tier: rng
    environment: dev
spec:
  containers:
  - name: rng-container
    image: duizhang/rng:1.0
  affinity:
    nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: zone
           operator: In
           values:
           - foo
           - bar
