apiVersion: v1
kind: Pod
metadata:
  name: rng-pod-first
  namespace: schedule-demo
  labels:
    app: myapp
    tier: rng
    environment: dev
spec:
  containers:
  - name: rng-container
    image: duizhang/rng:1.0

---

apiVersion: v1
kind: Pod
metadata:
  name: rng-pod-second
  namespace: schedule-demo
  labels:
    app: db
    tier: rng
    environment: dev
spec:
  containers:
  - name: rng-container-second
    image: duizhang/rng:1.0
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - {key: app,operator: In, values: ["myapp"]}

        topologyKey: duizhang
