apiVersion: v1
kind: Pod
metadata:
  name: rng-pod
  namespace: schedule-demo
  labels:
    app: myapp
    tier: rng
    environment: dev
spec:
  nodeSelector:
    zone: bj
  containers:
  - name: rng-container
    image: duizhang/rng:1.0
